package org.testngExamples;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.Reporter;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class TestNG_basics {
	WebDriver driver;
	@BeforeClass  //used for executing a method before any other test cases with @Test annotation are executed
	public void startUp() {
	System.setProperty("webdriver.chrome.driver", "C:\\Users\\REHMATH\\Downloads\\chromedriver_win32\\chromedriver.exe");
	driver = new ChromeDriver();
	}
	@AfterClass //this annotation is used for executing the method after all the test cases with @Test annotation are executed.
	public void tearDown() {
		driver.close();
	}
	@Test //In order to execute test case this annotation is used. 
	public void tc001() throws Exception {
		driver.navigate().to("Enter URL");
		//Reporter.log helps in printing statements in reports generated by testNG
		Reporter.log("Application opened"); 
		driver.findElement(By.name("txtUserName")).sendKeys("admin");
		driver.findElement(By.name("txtPassword")).sendKeys("admin");
		driver.findElement(By.name("Submit")).click();
		Thread.sleep(2000);
		Reporter.log("Login completed");
		driver.findElement(By.linkText("Logout")).click();
		Reporter.log("Logout Completed");
	}
}
